import {
  HeroItem,
  Project,
  AboutContent,
  AwardItem,
  JournalArticle,
  TeamMember,
  ContactInfo,
  SiteSettings,
} from "../lib/types";

export const INITIAL_HERO_ITEMS: HeroItem[] = [
  {
    id: "haven-1",
    image: "/projects/HAVEN/1-opt.jpg",
    title: "HAVEN",
    category: "RESIDENTIAL",
    year: "2025",
    meta: "RESIDENTIAL · 2025",
    projectSlug: "HAVEN",
    order: 1,
    visible: true,
  },
  {
    id: "haven-19",
    image: "/projects/HAVEN/19-opt.jpg",
    title: "HAVEN",
    category: "RESIDENTIAL",
    year: "2025",
    meta: "RESIDENTIAL · 2025",
    projectSlug: "HAVEN",
    order: 2,
    visible: true,
  },
  {
    id: "haven-28",
    image: "/projects/HAVEN/28-opt.jpg",
    title: "HAVEN",
    category: "RESIDENTIAL",
    year: "2025",
    meta: "RESIDENTIAL · 2025",
    projectSlug: "HAVEN",
    order: 3,
    visible: true,
  },
  {
    id: "haven-21",
    image: "/projects/HAVEN/21-opt.jpg",
    title: "HAVEN",
    category: "RESIDENTIAL",
    year: "2025",
    meta: "RESIDENTIAL · 2025",
    projectSlug: "HAVEN",
    order: 4,
    visible: true,
  },
  {
    id: "haven-8",
    image: "/projects/HAVEN/8-opt.jpg",
    title: "HAVEN",
    category: "RESIDENTIAL",
    year: "2025",
    meta: "RESIDENTIAL · 2025",
    projectSlug: "HAVEN",
    order: 5,
    visible: true,
  },
  {
    id: "haven-6",
    image: "/projects/HAVEN/6-opt.jpg",
    title: "HAVEN",
    category: "RESIDENTIAL",
    year: "2025",
    meta: "RESIDENTIAL · 2025",
    projectSlug: "HAVEN",
    order: 6,
    visible: true,
  },
  {
    id: "mausam-15",
    image: "/projects/MAUSAM_THE_HOUSE_OF_SEASONS/1_15-opt.jpg",
    title: "MAUSAM",
    category: "RESIDENTIAL",
    year: "2024",
    meta: "RESIDENTIAL · 2024",
    projectSlug: "MAUSAM_THE_HOUSE_OF_SEASONS",
    order: 7,
    visible: true,
  },
  {
    id: "haven-35",
    image: "/projects/HAVEN/35-opt.jpg",
    title: "HAVEN",
    category: "RESIDENTIAL",
    year: "2025",
    meta: "RESIDENTIAL · 2025",
    projectSlug: "HAVEN",
    order: 8,
    visible: true,
  },
  {
    id: "mausam-18",
    image: "/projects/MAUSAM_THE_HOUSE_OF_SEASONS/1_18-opt.jpg",
    title: "MAUSAM",
    category: "RESIDENTIAL",
    year: "2024",
    meta: "RESIDENTIAL · 2024",
    projectSlug: "MAUSAM_THE_HOUSE_OF_SEASONS",
    order: 9,
    visible: true,
  },
  {
    id: "haven-3",
    image: "/projects/HAVEN/3-opt.jpg",
    title: "HAVEN",
    category: "RESIDENTIAL",
    year: "2025",
    meta: "RESIDENTIAL · 2025",
    projectSlug: "HAVEN",
    order: 10,
    visible: true,
  },
  {
    id: "mausam-11",
    image: "/projects/MAUSAM_THE_HOUSE_OF_SEASONS/1_11-opt.jpg",
    title: "MAUSAM",
    category: "RESIDENTIAL",
    year: "2024",
    meta: "RESIDENTIAL · 2024",
    projectSlug: "MAUSAM_THE_HOUSE_OF_SEASONS",
    order: 11,
    visible: true,
  },
  {
    id: "mausam-41",
    image: "/projects/MAUSAM_THE_HOUSE_OF_SEASONS/1_41-opt.jpg",
    title: "MAUSAM",
    category: "RESIDENTIAL",
    year: "2024",
    meta: "RESIDENTIAL · 2024",
    projectSlug: "MAUSAM_THE_HOUSE_OF_SEASONS",
    order: 12,
    visible: true,
  },
  {
    id: "edavanna-14",
    image: "/projects/RESIDENCE_AT_EDAVANNA/Q14-opt.jpg",
    title: "RESIDENCE AT EDAVANNA",
    category: "RESIDENTIAL",
    year: "2024",
    meta: "RESIDENTIAL · 2024",
    projectSlug: "RESIDENCE_AT_EDAVANNA",
    order: 13,
    visible: true,
  },
  {
    id: "edavanna-2",
    image: "/projects/RESIDENCE_AT_EDAVANNA/Q2-opt.jpg",
    title: "RESIDENCE AT EDAVANNA",
    category: "RESIDENTIAL",
    year: "2024",
    meta: "RESIDENTIAL · 2024",
    projectSlug: "RESIDENCE_AT_EDAVANNA",
    order: 14,
    visible: true,
  },
  {
    id: "mausam-1",
    image: "/projects/MAUSAM_THE_HOUSE_OF_SEASONS/1_1-opt.jpg",
    title: "MAUSAM",
    category: "RESIDENTIAL",
    year: "2024",
    meta: "RESIDENTIAL · 2024",
    projectSlug: "MAUSAM_THE_HOUSE_OF_SEASONS",
    order: 15,
    visible: true,
  },
  {
    id: "edavanna-12",
    image: "/projects/RESIDENCE_AT_EDAVANNA/Q12-opt.jpg",
    title: "RESIDENCE AT EDAVANNA",
    category: "RESIDENTIAL",
    year: "2024",
    meta: "RESIDENTIAL · 2024",
    projectSlug: "RESIDENCE_AT_EDAVANNA",
    order: 16,
    visible: true,
  },
  {
    id: "edavanna-17",
    image: "/projects/RESIDENCE_AT_EDAVANNA/Q17-opt.jpg",
    title: "RESIDENCE AT EDAVANNA",
    category: "RESIDENTIAL",
    year: "2024",
    meta: "RESIDENTIAL · 2024",
    projectSlug: "RESIDENCE_AT_EDAVANNA",
    order: 17,
    visible: true,
  },
  {
    id: "edavanna-16",
    image: "/projects/RESIDENCE_AT_EDAVANNA/Q16-opt.jpg",
    title: "RESIDENCE AT EDAVANNA",
    category: "RESIDENTIAL",
    year: "2024",
    meta: "RESIDENTIAL · 2024",
    projectSlug: "RESIDENCE_AT_EDAVANNA",
    order: 18,
    visible: true,
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    slug: "HAVEN",
    title: "HAVEN",
    subtitle: "A quiet residential refuge anchored by laterite and filtered daylight.",
    editorialIntro: "A home that embraces its landscape, working with local materials and tropical climate to create a calm, grounded living environment for a contemporary family.",
    category: "Architecture & Interiors",
    year: "2025",
    location: "Kannur, Kerala, India",
    area: "3,263 sqft",
    leadArchitects: "Hafeez & Arjun",
    photography: "Abhimanyu KV",
    awards: ["Vanitha Veedu Architectural Awards 2026 - Silver: Category Residential Interior"],
    heroImage: "/projects/HAVEN/1-opt.jpg",
    summary:
      "HAVEN reflects the firm’s core design philosophy of simplicity and material restraint, expressed through a quiet palette of regional laterite, cement plaster, and honest minimal finishes.",
    narrative: [
      {
        heading: "Site Dialogue & Form",
        paragraphs: [
          "Conceived as a linear volume on an elevated site, the design deliberately resists dominating its natural context. Instead, it integrates an endemic laterite wall that serves simultaneously as compound boundary and building skin along the eastern edge, silently anchoring the communal living zones.",
          "Approached from the south, the house presents an earthy, grounded character with a sloping tiled roof that subtly references traditional vernacular typologies. A floating sit-out with tropical planting and a simple wooden bench offers a calm threshold, while layered floor planes extend into a porch terrace framing panoramic valley views.",
        ],
      },
      {
        heading: "Spatial Choreography & Light",
        paragraphs: [
          "Inside, spaces unfold linearly—living and dining flow seamlessly into an expanded kitchen, while private bedrooms branch off to the west, buffered by a family lounge and sculptural staircase. The layout remains open yet selectively screened for privacy.",
        ],
      },
      {
        heading: "Materiality & Climate",
        paragraphs: [
          "Natural ventilation and filtered daylight animate the interiors through calibrated apertures and the perforated laterite envelope, allowing the home to engage its tropical setting with quiet sensitivity and climatic responsiveness.",
        ],
      },
    ],
    gallery: [
      {
        src: "/projects/HAVEN/3-opt.jpg",
        alt: "HAVEN - Entrance threshold and tropical landscaping",
        caption: "Floating threshold with indigenous tropical flora framing the arrival sequence.",
        aspectRatio: "landscape",
      },
      {
        src: "/projects/HAVEN/8-opt.jpg",
        alt: "HAVEN - Vernacular sloping roofline and laterite masonry",
        caption: "Sloping clay-tiled roofline designed for torrential monsoon runoff.",
        aspectRatio: "landscape",
      },
      {
        src: "/projects/HAVEN/19-opt.jpg",
        alt: "HAVEN - Double height interior living court",
        caption: "Double-height central living court washing spaces in soft daylight.",
        aspectRatio: "portrait",
      },
      {
        src: "/projects/HAVEN/21-opt.jpg",
        alt: "HAVEN - Perforated laterite masonry screen",
        caption: "Perforated laterite jali modulating sunlight and ambient air breeze.",
        aspectRatio: "portrait",
      },
      {
        src: "/projects/HAVEN/27-opt.jpg",
        alt: "HAVEN - Minimal interior finishes and shadow play",
        caption: "Textural contrast between rough stone and hand-troweled lime plaster.",
        aspectRatio: "landscape",
      },
      {
        src: "/projects/HAVEN/35-opt.jpg",
        alt: "HAVEN - Evening perspective and illuminated volumes",
        caption: "Dusk perspective showing the glowing interior volumes against the landscape.",
        aspectRatio: "wide",
      },
    ],
    featured: true,
    visible: true,
    order: 1,
  },
  {
    slug: "MAUSAM_THE_HOUSE_OF_SEASONS",
    title: "Mausam — The House of Seasons",
    subtitle: "A contour-hugging home evolving with the rhythms of Kerala’s seasons.",
    category: "Residential Architecture",
    year: "2024",
    location: "Mannarkkad, Kozhikode, Kerala, India",
    area: "4,100 sqft",
    leadArchitects: "Hafeez & Arjun",
    photography: "Hamid MM",
    awards: ["The Merit List 2018-19 Citation", "National Award Commendation"],
    heroImage: "/projects/MAUSAM_THE_HOUSE_OF_SEASONS/1_15-opt.jpg",
    summary:
      "Conceived as a response to the growing misconception that good architecture must appear expensive, the house reclaims simplicity, climatic responsiveness, and vernacular sensibilities within a sloping rubber plantation.",
    narrative: [
      {
        heading: "Contour-Responsive Architecture",
        paragraphs: [
          "Designed for a retired army officer and his family, the home effortlessly adapts between intimate living for two and larger multi-generational family gatherings. Spaces are arranged along the natural ground contour in three split levels, interconnected by a central stair with flexible common living areas.",
          "By nestling into the earth rather than clearing the terrain, the house preserves existing plantation slopes and allows natural subterranean cooling to temper interior microclimates throughout scorching summer months.",
        ],
      },
      {
        heading: "Material Truth & Microclimates",
        paragraphs: [
          "Vernacular materials—laterite stone, terracotta tiles, and reclaimed timber—along with porous masonry jalis ensure thermal comfort, cross-ventilation, and dynamic dappled light.",
          "Blending into its lush topography, the house evolves with the seasons—refreshingly cool during hot pre-monsoon months, expressive and sheltering in heavy rains, and quietly alive through shifting light and mountain breeze.",
        ],
      },
    ],
    gallery: [
      {
        src: "/projects/MAUSAM_THE_HOUSE_OF_SEASONS/1_1-opt.jpg",
        alt: "Mausam - Slope integration and exterior volume",
        caption: "Split-level volume nestled along the natural slope of the rubber plantation.",
        aspectRatio: "landscape",
      },
      {
        src: "/projects/MAUSAM_THE_HOUSE_OF_SEASONS/1_11-opt.jpg",
        alt: "Mausam - Terracotta jali screen and light interplay",
        caption: "Perforated brickwork jali framing light and screening afternoon sun.",
        aspectRatio: "portrait",
      },
      {
        src: "/projects/MAUSAM_THE_HOUSE_OF_SEASONS/1_18-opt.jpg",
        alt: "Mausam - Central staircase connecting split levels",
        caption: "Central stair linking intimate split levels across the interior core.",
        aspectRatio: "portrait",
      },
      {
        src: "/projects/MAUSAM_THE_HOUSE_OF_SEASONS/1_26-opt.jpg",
        alt: "Mausam - Unfinished laterite blockwork detail",
        caption: "Raw regional laterite laid in honest masonry bond.",
        aspectRatio: "landscape",
      },
      {
        src: "/projects/MAUSAM_THE_HOUSE_OF_SEASONS/1_38-opt.jpg",
        alt: "Mausam - Courtyard and rainwater catchment aperture",
        caption: "Internal court allowing seasonal rainfall to bring scent and sound inside.",
        aspectRatio: "landscape",
      },
      {
        src: "/projects/MAUSAM_THE_HOUSE_OF_SEASONS/1_42-opt.jpg",
        alt: "Mausam - Deep verandah and exterior shelter",
        caption: "Generous roof overhangs shielding living spaces from tropical glare.",
        aspectRatio: "wide",
      },
    ],
    featured: true,
    visible: true,
    order: 2,
  },
  {
    slug: "RESIDENCE_AT_EDAVANNA",
    title: "Residence at Edavanna",
    subtitle: "A humble family home designed for meaningful ecological life and community roots.",
    category: "Residential Architecture",
    year: "2024",
    location: "Edavanna, Malappuram, Kerala, India",
    area: "3,014 sqft",
    client: "Mr. Ashiq & Mrs. Sibla",
    leadArchitects: "Hafeez & Arjun",
    photography: "Edwin James",
    awards: ["IIA Kerala State Awards for Excellence in Architecture Citation"],
    heroImage: "/projects/RESIDENCE_AT_EDAVANNA/Q14-opt.jpg",
    summary:
      "Set within a landscape reminiscent of 1980s Kerala homes, the residence sits at the heart of a generous plot, prioritizing gardens, kitchen cultivation, and ecological grounding beyond ornamentation.",
    narrative: [
      {
        heading: "Ground-Oriented Living",
        paragraphs: [
          "Evoking the quiet charm of traditional Kerala domestic life, the house is designed for a young family choosing to live close to their ancestral roots. Positioned away from property boundaries, the plan is largely ground-oriented, with essential living spaces below and minimal private sanctuaries above.",
          "The layout organizes along an axial spine, with courtyards and transition passages dividing the home into zones of varying privacy while preserving seamless visual connections across garden patches.",
        ],
      },
      {
        heading: "Courtyards & Material Honesty",
        paragraphs: [
          "Internal courtyards introduce gentle daylight, cooling airflow, and moments of contemplation. The restrained palette of unplastered brick, board-formed concrete, and native hardwood reinforces a humble character tailored to everyday life.",
          "Over time, tropical rains and organic patina will embed the home deeper into its verdant setting, creating a dwelling that ages with grace and dignity.",
        ],
      },
    ],
    gallery: [
      {
        src: "/projects/RESIDENCE_AT_EDAVANNA/Q2-opt.jpg",
        alt: "Residence at Edavanna - Central courtyard and lush greenery",
        caption: "Garden interface creating a calm, sheltered microclimate.",
        aspectRatio: "landscape",
      },
      {
        src: "/projects/RESIDENCE_AT_EDAVANNA/Q8-opt.jpg",
        alt: "Residence at Edavanna - Axial circulation corridor",
        caption: "Axial circulation connecting internal courts with family living spaces.",
        aspectRatio: "portrait",
      },
      {
        src: "/projects/RESIDENCE_AT_EDAVANNA/Q12-opt.jpg",
        alt: "Residence at Edavanna - Board formed concrete and masonry",
        caption: "Board-formed concrete elements framing honest brick surfaces.",
        aspectRatio: "portrait",
      },
      {
        src: "/projects/RESIDENCE_AT_EDAVANNA/Q16-opt.jpg",
        alt: "Residence at Edavanna - Overhanging eaves and roof profile",
        caption: "Deep overhanging eaves inspired by traditional Kerala tharavadu.",
        aspectRatio: "landscape",
      },
      {
        src: "/projects/RESIDENCE_AT_EDAVANNA/Q21-opt.jpg",
        alt: "Residence at Edavanna - Cross-ventilated living area",
        caption: "Living room oriented to receive continuous cross-ventilation breezes.",
        aspectRatio: "landscape",
      },
      {
        src: "/projects/RESIDENCE_AT_EDAVANNA/Q26-opt.jpg",
        alt: "Residence at Edavanna - Twilight perspective among trees",
        caption: "Evening silhouette quietly resting within the canopy of coconut palms.",
        aspectRatio: "wide",
      },
    ],
    featured: true,
    visible: true,
    order: 3,
  },
  {
    slug: "SCREEN_THE_LANTERN_HOUSE",
    title: "Screen: The Lantern House",
    subtitle: "A glowing perforated residential screen that harmonizes privacy and openness.",
    category: "Residential Architecture",
    year: "2023 - 2024",
    location: "Tirur, Malappuram, Kerala, India",
    area: "3,500 sqft",
    leadArchitects: "Hafeez & Arjun",
    photography: "Abhimanyu KV",
    awards: [
      "Vanitha Veedu Architectural Awards 2024 - Silver: Category Residential",
      "IIID Kerala Regional Chapter Awards 2023 - Runner up: Category Residential",
      "IIA Kerala State Awards for Excellence in Architecture 2023 - Commendation",
    ],
    heroImage: "/projects/HAVEN/28-opt.jpg",
    summary:
      "A celebration of perforated masonry screens and internal courtyards, designed to offer sanctuary and microclimatic passive cooling in a tightly packed urban neighborhood.",
    narrative: [
      {
        heading: "The Perforated Screen",
        paragraphs: [
          "Located in an active neighborhood in Tirur, the Lantern House negotiates the tension between urban exposure and domestic intimacy. The primary facade is wrapped in a perforated tectonic screen that acts as an environmental filter.",
          "During the day, the screen breaks harsh tropical sunlight into delicate dappled shadows, while at night, internal lights transform the residence into a warm, glowing lantern on the street.",
        ],
      },
      {
        heading: "Courtyard Core",
        paragraphs: [
          "Internally, all social spaces wrap around an open-to-sky courtyard. The stack effect created by this central void pulls fresh air continuously through the lower living areas, exhausting heat through upper clerestories.",
          "The restrained palette of polished concrete floors, lime-washed walls, and teak wood details imparts a quiet, contemplative atmosphere throughout.",
        ],
      },
    ],
    gallery: [
      {
        src: "/projects/HAVEN/28-opt.jpg",
        alt: "The Lantern House - Perforated screen elevation at dusk",
        caption: "The perforated masonry envelope illuminating like a lantern at dusk.",
        aspectRatio: "landscape",
      },
      {
        src: "/projects/HAVEN/35-opt.jpg",
        alt: "The Lantern House - Dynamic shadow play across concrete",
        caption: "Geometric brick jali casting shifting shadow art across the floor.",
        aspectRatio: "portrait",
      },
      {
        src: "/projects/HAVEN/19-opt.jpg",
        alt: "The Lantern House - Central courtyard atrium",
        caption: "Open-to-sky central courtyard atrium promoting natural passive cooling.",
        aspectRatio: "portrait",
      },
      {
        src: "/projects/HAVEN/21-opt.jpg",
        alt: "The Lantern House - Transition corridor and screened openings",
        caption: "Circulation corridors buffered from external noise by textured screens.",
        aspectRatio: "landscape",
      },
    ],
    featured: false,
    visible: true,
    order: 4,
  },
  {
    slug: "KADALAS_THE_SEA_VIEW_CAFE",
    title: "Kadalas - The Sea View Cafe",
    subtitle: "A beachfront hospitality space framed by panoramic sea vistas and maritime craft.",
    category: "Hospitality & Leisure Interiors",
    year: "2019 - 2023",
    location: "South Beach, Calicut, Kerala, India",
    area: "1,800 sqft",
    leadArchitects: "Hafeez & Arjun",
    photography: "Prasanth Mohan",
    awards: [
      "Forbes India Design Awards 2019 - 'Best Retail & Hospitality Interiors' Commendation",
      "IID Design Excellence Awards 2019 - Winner Zone 1 (Leisure & Entertainment)",
      "IIA Kerala State Awards for Excellence in Architecture 2021 - Commendation",
    ],
    heroImage: "/projects/HAVEN/6-opt.jpg",
    summary:
      "A sensory culinary destination perched along Calicut’s historic coastline, celebrating maritime materials, raw wood, and unobstructed horizons over the Arabian Sea.",
    narrative: [
      {
        heading: "Coastal Architecture & Memory",
        paragraphs: [
          "Calicut's South Beach has a centuries-old maritime history of trade, seafaring, and spice culture. Kadalas was envisioned as a light, non-intrusive coastal pavilion that pays homage to traditional boat-building craft.",
          "Constructed with reclaimed boat timber, exposed steel, and weathered stone, the cafe allows salty ocean breezes to filter freely through the open seating terraces.",
        ],
      },
      {
        heading: "Immersive Seaward Vistas",
        paragraphs: [
          "The dining layout steps down toward the water, giving every table an uninterrupted frame of crashing waves and sunsets over the Arabian Sea.",
          "Minimalist ambient lighting and acoustic damping ensure the sound of the ocean remains the primary soundtrack of the dining experience.",
        ],
      },
    ],
    gallery: [
      {
        src: "/projects/HAVEN/6-opt.jpg",
        alt: "Kadalas - Panoramic beachfront dining deck",
        caption: "Open beachfront dining deck framing dramatic sunsets over the Arabian Sea.",
        aspectRatio: "landscape",
      },
      {
        src: "/projects/HAVEN/1-opt.jpg",
        alt: "Kadalas - Reclaimed timber and coastal joinery",
        caption: "Reclaimed wooden joinery inspired by traditional Malabar boat craftsmanship.",
        aspectRatio: "landscape",
      },
      {
        src: "/projects/HAVEN/3-opt.jpg",
        alt: "Kadalas - Ocean breeze interface and sheltered seating",
        caption: "Sheltered seating pavilion designed for open cross-ventilation.",
        aspectRatio: "portrait",
      },
      {
        src: "/projects/HAVEN/8-opt.jpg",
        alt: "Kadalas - Evening ambient lighting and atmosphere",
        caption: "Warm evening glow harmonizing with the natural sound of breaking tides.",
        aspectRatio: "landscape",
      },
    ],
    featured: false,
    visible: true,
    order: 5,
  },
  {
    slug: "REVIVING_THE_SPIRIT_OF_A_PLACE",
    title: "Reviving The Spirit of A Place",
    subtitle: "Story of an Abandoned Laterite Quarry restored into a thriving ecological sanctuary.",
    category: "Landscape & Ecological Design",
    year: "2020 - 2022",
    location: "Malappuram, Kerala, India",
    area: "12 Acres",
    leadArchitects: "Hafeez & Arjun",
    photography: "Edwin James",
    awards: [
      "Kohler Bold Design Awards 2022 - Winner: Category Landscape Design",
      "IIA Kerala State Awards for Excellence in Architecture 2021 - Gold Leaf: Category Landscape",
      "IIA National Awards for Excellence in Architecture 2020 - Shortlisted",
    ],
    heroImage: "/projects/RESIDENCE_AT_EDAVANNA/Q16-opt.jpg",
    summary:
      "A benchmark regenerative landscape project transforming a degraded, abandoned laterite stone quarry into a biodiverse ecological sanctuary with water catchment reservoirs.",
    narrative: [
      {
        heading: "Regenerating Scarred Landscapes",
        paragraphs: [
          "Decades of uncontrolled open-cast quarrying had left the 12-acre site barren, eroded, and stripped of topsoil. Zero Studio approached the intervention not as building on land, but as healing geological trauma.",
          "By surveying rainwater flow patterns and natural contours, the excavation pits were sculpted into cascading retention reservoirs that collect monsoon runoff and replenish regional groundwater tables.",
        ],
      },
      {
        heading: "Ecological Succession & Honest Pavilions",
        paragraphs: [
          "Native endemic flora, drought-resistant grasses, and wetland reed-beds were introduced to stabilize slopes and invite indigenous birds, butterflies, and amphibians back to the terrain.",
          "Minimalist stone steps and unembellished laterite pavilions provide human visitors with quiet contemplative paths through the regenerated wilderness without disrupting the fragile new ecology.",
        ],
      },
    ],
    gallery: [
      {
        src: "/projects/RESIDENCE_AT_EDAVANNA/Q16-opt.jpg",
        alt: "Reviving The Spirit of A Place - Restored laterite quarry terrain",
        caption: "Sculpted stone terraces retaining water and transforming barren rock into a living wetland.",
        aspectRatio: "landscape",
      },
      {
        src: "/projects/RESIDENCE_AT_EDAVANNA/Q2-opt.jpg",
        alt: "Reviving The Spirit of A Place - Native vegetation and water bodies",
        caption: "Regenerated endemic forest canopy cradling monsoon water catchment ponds.",
        aspectRatio: "portrait",
      },
      {
        src: "/projects/RESIDENCE_AT_EDAVANNA/Q24-opt.jpg",
        alt: "Reviving The Spirit of A Place - Contemplative stone pathways",
        caption: "Minimalist stone walkways harmonizing with natural geological formations.",
        aspectRatio: "portrait",
      },
      {
        src: "/projects/RESIDENCE_AT_EDAVANNA/Q8-opt.jpg",
        alt: "Reviving The Spirit of A Place - Ecological restoration panoramic",
        caption: "Panoramic vista of the 12-acre restored sanctuary thriving with biodiversity.",
        aspectRatio: "wide",
      },
    ],
    featured: false,
    visible: true,
    order: 6,
  },
];

export const INITIAL_ABOUT: AboutContent = {
  heading: "The Studio",
  paragraph1:
    "Zero studio is a creative design studio driving itself forward with a perception to experiment with architecture under the varying contexts of need and, most importantly, the user. Founded in 2013 by the visionary duo Ar.Hamid MM & Ar.Hafeef PK, the studio is now led by Ar.Shabna & Ar.Nidhinraj KJ.",
  paragraph2:
    "We approach every project as a unique opportunity to converse with nature, finding an adaptive balance between functionality, aesthetics, context, climate, and materials. We love to call our practice an art studio, where the character of our designs varies vibrantly, never restricted by a single ideology, allowing architecture to remain a subtle, evolving blend of ideas.",
  leadArchitects: "Ar. Hamid MM, Ar. Hafeef PK, Ar. Shabna, Ar. Nidhinraj KJ",
  stats: [
    { label: "Founded", value: "2013" },
    { label: "National & State Citations", value: "25+" },
    { label: "Completed Works", value: "40+" },
  ],
};

export const INITIAL_AWARDS: AwardItem[] = [
  // Curated 6 for homepage preview
  {
    id: "award-curated-1",
    number: "01",
    award: "Silver Leaf Award",
    project: "HAVEN, Kannur",
    organization: "Vanitha Veedu Architectural Awards",
    category: "Residential Interior",
    year: "2026",
    order: 1,
    curated: true,
    visible: true,
    type: "curated",
  },
  {
    id: "award-curated-2",
    number: "02",
    award: "Best Young Architect from Kerala",
    project: "Ar. Hamid MM & Zero Studio Team",
    organization: "IIA National Awards for Excellence in Architecture",
    category: "Young Architect Award",
    year: "2024",
    order: 2,
    curated: true,
    visible: true,
    type: "curated",
  },
  {
    id: "award-curated-3",
    number: "03",
    award: "Commendation Award",
    project: "Screen: The Lantern House, Tirur",
    organization: "IIA Kerala State Awards for Excellence",
    category: "Residential Interior",
    year: "2023",
    order: 3,
    curated: true,
    visible: true,
    type: "curated",
  },
  {
    id: "award-curated-4",
    number: "04",
    award: "Winner — Landscape Design",
    project: "Reviving the Spirit of a Place (Quarry)",
    organization: "Kohler Bold Design Awards",
    category: "Responsible Architecture & Landscape",
    year: "2022",
    order: 4,
    curated: true,
    visible: true,
    type: "curated",
  },
  {
    id: "award-curated-5",
    number: "05",
    award: "National Winner",
    project: "Edavani: Redefining a Tribal Hamlet",
    organization: "IIA National Awards for Excellence in Architecture",
    category: "Architecture Unbuilt",
    year: "2020",
    order: 5,
    curated: true,
    visible: true,
    type: "curated",
  },
  {
    id: "award-curated-6",
    number: "06",
    award: "Special Commendation",
    project: "Kadalas: The Sea View Cafe, South Beach",
    organization: "Forbes India Design Awards",
    category: "Retail & Hospitality Interiors",
    year: "2019",
    order: 6,
    curated: true,
    visible: true,
    type: "curated",
  },
  // Additional comprehensive project recognitions
  {
    id: "award-proj-1",
    award: "Silver Category Residential Interior",
    project: "HAVEN, Kannur, Kerala",
    organization: "Vanitha Veedu Architectural Awards 2026",
    category: "Residential Interior",
    year: "2026",
    order: 7,
    curated: false,
    visible: true,
    type: "project",
  },
  {
    id: "award-proj-2",
    award: "Silver (Residential) & Commendation",
    project: "Screen: the LANTERN house, Tirur, Kerala",
    organization: "Vanitha Veedu & IIA Kerala State Awards",
    category: "Residential",
    year: "2023 - 2024",
    order: 8,
    curated: false,
    visible: true,
    type: "project",
  },
  {
    id: "award-proj-3",
    award: "Winner Landscape & Gold Leaf",
    project: "Reviving the spirit of a place - Story of An Abandoned Laterite Quarry",
    organization: "Kohler Bold Design Awards & IIA Kerala",
    category: "Responsible Architecture & Landscape",
    year: "2020 - 2022",
    order: 9,
    curated: false,
    visible: true,
    type: "project",
  },
  {
    id: "award-proj-4",
    award: "National Winner Architecture Unbuilt",
    project: "Edavani : Redefining a Tribal Hamlet, Attappady, Kerala",
    organization: "IIA National Awards for Excellence in Architecture",
    category: "Architecture Unbuilt",
    year: "2020 - 2021",
    order: 10,
    curated: false,
    visible: true,
    type: "project",
  },
  {
    id: "award-proj-5",
    award: "Special Commendation & National Runner-up",
    project: "Kadalas - The Sea view cafe, South Beach, Calicut, Kerala",
    organization: "Forbes India Design Awards & IID Awards",
    category: "Hospitality & Leisure Interiors",
    year: "2018 - 2023",
    order: 11,
    curated: false,
    visible: true,
    type: "project",
  },
  {
    id: "award-proj-6",
    award: "The Merit List & Ace Alpha Award",
    project: "Mausam - The house of seasons",
    organization: "The Merit List & Ace Alpha Awards",
    category: "Residential Affordable",
    year: "2017 - 2019",
    order: 12,
    curated: false,
    visible: true,
    type: "project",
  },
  {
    id: "award-proj-7",
    award: "Award for Best Renovated House - Winner",
    project: "Residence for Mr. Biju Mathew, Perinthalmanna, Kerala",
    organization: "Vanitha Veedu Architecture Awards",
    category: "Renovated Residential",
    year: "2017",
    order: 13,
    curated: false,
    visible: true,
    type: "project",
  },
  {
    id: "award-proj-8",
    award: "Best Unbuilt Design & National Commendation",
    project: "Green Lattice - The Tower of Remembrance; Seethi Haji Memorial Cultural Center",
    organization: "Archi Design & IIA National Awards",
    category: "Architecture Unbuilt",
    year: "2014 - 2016",
    order: 14,
    curated: false,
    visible: true,
    type: "project",
  },
  {
    id: "award-proj-9",
    award: "Commendation & National Shortlist",
    project: "The Temple of Knowledge: A Tribute to the father of Malayalam, Tirur, Kerala",
    organization: "IIA National & Kerala State Awards",
    category: "Architecture Unbuilt",
    year: "2014 - 2016",
    order: 15,
    curated: false,
    visible: true,
    type: "project",
  },
  {
    id: "award-proj-10",
    award: "Golden Leaf Award",
    project: "A Reminiscing Walk through Valiyangadi: history that is retained and revived, Malappuram",
    organization: "IIA-Royale State Awards for Excellence",
    category: "Urban / Heritage",
    year: "2013 - 2016",
    order: 16,
    curated: false,
    visible: true,
    type: "project",
  },
  // Studio honors
  {
    id: "honor-1",
    award: "Listing for top 50 gen-next architects",
    project: "i-GEN Design Forum",
    organization: "Architect and Interiors India magazine",
    category: "Practice Honor",
    year: "2016",
    order: 17,
    curated: false,
    visible: true,
    type: "honor",
  },
  {
    id: "honor-2",
    award: "The award for Best Young Architect",
    project: "Vanitha Veedu Architecture Awards",
    organization: "Vanitha Veedu",
    category: "Young Architect Award",
    year: "2017",
    order: 18,
    curated: false,
    visible: true,
    type: "honor",
  },
  {
    id: "honor-3",
    award: "Selected among '20 under 35'",
    project: "Design X Design Annual Exhibition",
    organization: "Design X Design",
    category: "National Exhibition",
    year: "2018",
    order: 19,
    curated: false,
    visible: true,
    type: "honor",
  },
  {
    id: "honor-4",
    award: "Startup of the year Award 2018",
    project: "Saint-Gobain & Economic Times",
    organization: "Smart Green Summit",
    category: "Sustainability & Practice",
    year: "2018",
    order: 20,
    curated: false,
    visible: true,
    type: "honor",
  },
  {
    id: "honor-5",
    award: "ID Honours Award: Biophilic Design",
    project: "India Design ID",
    organization: "ID Honours",
    category: "Biophilic Design",
    year: "2023",
    order: 21,
    curated: false,
    visible: true,
    type: "honor",
  },
  {
    id: "honor-6",
    award: "Listing for top 50 gen-next architects",
    project: "i-GEN Design Forum 2023",
    organization: "Architect and Interiors India magazine",
    category: "Practice Honor",
    year: "2023",
    order: 22,
    curated: false,
    visible: true,
    type: "honor",
  },
  {
    id: "honor-7",
    award: "IIA National award for best Young architect from Kerala Chapter",
    project: "IIA National Awards",
    organization: "Indian Institute of Architects",
    category: "Young Architect Award",
    year: "2024",
    order: 23,
    curated: false,
    visible: true,
    type: "honor",
  },
];

export const INITIAL_JOURNAL: JournalArticle[] = [
  {
    title: "The Architecture of Quiet Spaces",
    slug: "the-architecture-of-quiet-spaces",
    category: "Architecture & Context",
    date: "05 OCTOBER 2026",
    excerpt:
      "Exploring how light, proportion and material restraint create spaces that feel calm, contemplative and deeply connected to their surroundings.",
    image: "/projects/HAVEN/1-opt.jpg",
    content: {
      intro:
        "In an era of relentless sensory stimuli, architecture has an imperative to offer refuge. Quietness in built form is not the mere absence of sound or ornament; it is a deliberate spatial calibration of daylight, thermal comfort, and raw material truth.",
      paragraphs: [
        "When designing residential and cultural enclosures, our inquiry invariably begins with threshold conditions. How does one transition from the public realm into the private realm? Through elongated arrival paths, perforated masonry screens, and calibrated apertures, the eye is invited to slow down and attune to natural rhythms.",
        "The interplay between textured laterite stone and smooth lime plaster introduces a tangible weight to walls. Shadows become tactile. As daylight shifts across the textured surfaces, room geometries feel alive yet anchored, never demanding attention but silently cradling daily human existence.",
        "True architectural silence is achieved when structure and landscape negotiate an unhurried dialogue. Courtyards wrapped in endemic greenery allow seasonal monsoon showers to filter scent, humidity, and reflection directly into the living core, dissolving boundaries between enclosure and earth.",
      ],
      secondaryImage: "/projects/HAVEN/27-opt.jpg",
      secondaryImageCaption:
        "Filtered daylight washing over minimal masonry surfaces in the central court.",
    },
    featured: true,
    visible: true,
    order: 1,
  },
  {
    title: "Tactility of Laterite and Exposed Concrete",
    slug: "tactility-of-laterite-and-exposed-concrete",
    category: "Material & Craft",
    date: "18 SEPTEMBER 2026",
    excerpt:
      "Why indigenous stone and honest cast surfaces ground tropical architecture, imparting dignity that patinas gracefully over decades.",
    image: "/projects/RESIDENCE_AT_EDAVANNA/Q16-opt.jpg",
    content: {
      intro:
        "Materials possess memory and geographic origin. Laterite, quarried directly from the regional soil of Kerala, carries with it an earthy warmth that synthetic composites can never replicate.",
      paragraphs: [
        "In our practice, material selection is never purely aesthetic; it is structural, climatic, and ethical. By leaving laterite and board-formed concrete unfinished, we acknowledge the passage of time. Tropical rains, humid winds, and organic moss gradually age the envelope, embedding the building into its terrain rather than fighting environmental wear.",
        "Craftsmanship bridges the gap between raw stone and contemporary precision. Working alongside regional stonemasons, we explore non-standard bonds and perforated jali screens. These porous masonry compositions allow the wall to breathe while sculpting geometric shadows across cast concrete floors.",
        "The juxtaposition of cold exposed concrete with warm porous laterite establishes a dialogue between tectonic permanence and vernacular familiarity, grounding contemporary living in geological heritage.",
      ],
      secondaryImage: "/projects/RESIDENCE_AT_EDAVANNA/Q2-opt.jpg",
      secondaryImageCaption:
        "Grounded masonry and deep eaves sheltering living spaces from tropical glare.",
    },
    featured: true,
    visible: true,
    order: 2,
  },
  {
    title: "Breathing Walls and Tropical Microclimates",
    slug: "breathing-walls-and-tropical-microclimates",
    category: "Climate Responsive Design",
    date: "28 AUGUST 2026",
    excerpt:
      "Passive cooling strategies, perforated envelopes and cross-ventilation techniques engineered for high-humidity monsoon landscapes.",
    image: "/projects/MAUSAM_THE_HOUSE_OF_SEASONS/1_18-opt.jpg",
    content: {
      intro:
        "Designing in the tropics requires surrendering to climate rather than resisting it. Instead of hermetically sealing buildings behind mechanical air conditioning, architecture must act as a breathable membrane.",
      paragraphs: [
        "The traditional vernacular courtyard house understood stack effect centuries ago. By combining central open-to-sky courts with low-intake perimeter vents, rising heat naturally exhausts upwards, drawing cooler subterranean air across living levels.",
        "Our perforated brick and terracotta screen configurations act as thermal heat sinks. During sweltering afternoon hours, the mass absorbs radiant heat while inducing Venturi airflow through microscopic apertures, cooling ambient indoor air by several degrees without mechanical intervention.",
        "Deep roof overhangs and timber louvers deflect torrential monsoon downpours while keeping openings wide open, allowing occupants to savor the rain without water ingress.",
      ],
      secondaryImage: "/projects/HAVEN/3-opt.jpg",
      secondaryImageCaption:
        "Shaded linear verandahs creating thermal buffer zones against intense equatorial sun.",
    },
    featured: true,
    visible: true,
    order: 3,
  },
  {
    title: "Inhabiting the Threshold: Verandahs and Courtyards",
    slug: "inhabiting-the-threshold-verandahs-and-courtyards",
    category: "Residential Architecture",
    date: "14 JULY 2026",
    excerpt:
      "The intermediate zone between interior shelter and outdoor nature as the true communal heart of the modern Indian home.",
    image: "/projects/RESIDENCE_AT_EDAVANNA/Q2-opt.jpg",
    content: {
      intro:
        "Domestic life in the sub-continent has never unfolded strictly within four enclosed walls. The verandah, or 'thinnai', has always been the primary setting for community, contemplation, and afternoon repose.",
      paragraphs: [
        "When reinterpreting residential typologies, we treat the perimeter not as a boundary wall, but as an inhabited spatial threshold. Deep cantilevered eaves protect built-in stone benches, where morning tea and quiet reading occur in direct contact with garden vegetation.",
        "Internal courtyards provide a complementary interior threshold. They introduce sky, rain, and nocturnal breezes into the heart of the dwelling, organizing private family quarters around an ever-changing natural stage.",
        "By prioritizing these intermediate zones, contemporary houses retain their familial intimacy while maintaining an expansive, unconfined relationship with the natural surroundings.",
      ],
      secondaryImage: "/projects/HAVEN/1-opt.jpg",
      secondaryImageCaption:
        "The entrance threshold framed by vernacular rooflines and laterite landscape walls.",
    },
    featured: false,
    visible: true,
    order: 4,
  },
  {
    title: "Drawing From the Land: Our Intuitive Sketch to Form",
    slug: "drawing-from-the-land-our-intuitive-sketch-to-form",
    category: "Design Process",
    date: "02 JUNE 2026",
    excerpt:
      "How site contours, existing tree canopies, and sun paths dictate the initial strokes of our architectural concepts.",
    image: "/projects/HAVEN/27-opt.jpg",
    content: {
      intro:
        "Every architectural design begins on site, long before a computer model is rendered. We walk the contours, locate mature trees, trace prevailing breezes, and observe where the afternoon light pools.",
      paragraphs: [
        "Hand drafting remains vital in our studio because the friction of graphite against paper introduces a slower, more deliberate contemplation of proportion and human scale. An intuitive sketch captures spatial sentiment in ways a digital grid cannot.",
        "We treat existing natural topography not as an obstacle to be flattened, but as the primary author of spatial hierarchy. Staggered floor plates, sunken living pits, and bridges that veer around existing mahogany trees are direct responses to the original contours of the site.",
        "This iterative dialogue between ground truth and architectural intention ensures that each finished project feels inevitable—as if it emerged organically from the terrain.",
      ],
      secondaryImage: "/projects/RESIDENCE_AT_EDAVANNA/Q16-opt.jpg",
      secondaryImageCaption:
        "Masonry screens detailed directly from full-scale mockups in the studio workshop.",
    },
    featured: false,
    visible: true,
    order: 5,
  },
  {
    title: "Integrating the Living Landscape as an Architectural Skin",
    slug: "integrating-the-living-landscape-as-an-architectural-skin",
    category: "Nature & Architecture",
    date: "19 APRIL 2026",
    excerpt:
      "Dissolving the division between garden and room through endemic flora, reflective water bodies, and climatic envelopes.",
    image: "/projects/HAVEN/3-opt.jpg",
    content: {
      intro:
        "Architecture should not sit upon the earth as a detached sculpture; it should root itself within the ecology of its place, allowing vegetation to become an integral structural and environmental material.",
      paragraphs: [
        "Tropical landscaping is not decorative dressing applied after construction. In our designs, planter beds, creeping vines, and rainwater retention basins are cast directly into the structural slabs during the earliest concrete pours.",
        "Living foliage provides superior solar insulation. Green curtains of hanging thunbergia and bougainvillea filter harsh glare into dappled light, reducing indoor ambient temperatures while generating gentle auditory rustle in the breeze.",
        "By designing houses that actively invite nature inside, architecture ceases to be an enclosure and becomes an ecosystem supporting human well-being and biodiversity.",
      ],
      secondaryImage: "/projects/MAUSAM_THE_HOUSE_OF_SEASONS/1_18-opt.jpg",
      secondaryImageCaption:
        "Central water court reflecting natural daylight into surrounding living pavilions.",
    },
    featured: false,
    visible: true,
    order: 6,
  },
];

export const INITIAL_TEAM: TeamMember[] = [
  {
    id: "team-1",
    name: "Ar. Hamid MM",
    role: "Founding Principal Architect",
    bio: "Co-founded Zero Studio in 2013. A visionary architect whose charismatic spirit and passion for material honesty established the fundamental philosophies of the studio.",
    order: 1,
    visible: true,
  },
  {
    id: "team-2",
    name: "Ar. Hafeef PK",
    role: "Founding Principal Architect",
    bio: "Co-founded Zero Studio in 2013. Instrumental in driving the studio's early experimental projects, vernacular exploration, and adaptive ecological architecture.",
    order: 2,
    visible: true,
  },
  {
    id: "team-3",
    name: "Ar. Shabna",
    role: "Lead Principal Architect",
    bio: "Currently steering Zero Studio's design direction, focusing on nuanced residential and spatial interventions that dialogue seamlessly with regional climate and craft.",
    order: 3,
    visible: true,
  },
  {
    id: "team-4",
    name: "Ar. Nidhinraj KJ",
    role: "Lead Principal Architect",
    bio: "Leads technical design and architectural discourse at Zero Studio, emphasizing tectonics, passive microclimatic cooling, and honest vernacular construction.",
    order: 4,
    visible: true,
  },
];

export const INITIAL_CONTACT: ContactInfo = {
  heading: "Start a project",
  lead: "We'd love to hear about your project.",
  emailGeneral: "mail@zerostudio.org",
  emailJobs: "jobs@zerostudio.org",
  phone: "+91 9447751826 · +91 8129355855",
  address:
    "#1/3793, East hill Road, Chakkorathukulam,\nEranhippalam P.O, Nadakkave, Kozhikode, Kerala 673006",
  mapLink: "https://maps.app.goo.gl/poxkV6PNkGL9cJsSA",
  instagramUrl: "https://www.instagram.com/zerostudioofficial",
  facebookUrl: "https://www.facebook.com/zerostudioofficial/",
};

export const INITIAL_SETTINGS: SiteSettings = {
  siteTitle: "Zero Studio Architectures",
  siteDescription:
    "Zero Studio Architectures designs homes, cultural spaces and workplaces with clear plans and honest materials.",
  logoUrl: "/ZERO-LOGO.png",
  faviconUrl: "/favicon.ico",
  defaultOgImage: "/projects/HAVEN/1-opt.jpg",
  instagramUrl: "https://www.instagram.com/zerostudioofficial",
  facebookUrl: "https://www.facebook.com/zerostudioofficial/",
};
